import type { Vehicle } from "$lib/types/vehicle.type";


export const brands = [
  { id: 1, brand: 'Fiat' },
  { id: 2, brand: 'Volkswagen' },
  { id: 3, brand: 'Chevrolet' },
  { id: 4, brand: 'Hyundai' },
  { id: 5, brand: 'Toyota' },
  { id: 6, brand: 'Renault' },
  { id: 7, brand: 'Jeep' },
  { id: 8, brand: 'Honda' },
  { id: 9, brand: 'Nissan' },
  { id: 10, brand: 'BYD' },
  { id: 11, brand: 'Caoa Chery' },
  { id: 12, brand: 'Ford' },
  { id: 13, brand: 'Citroën' },
  { id: 14, brand: 'Peugeot' },
  { id: 15, brand: 'BMW' },
  { id: 16, brand: 'Mercedes-Benz' },
  { id: 17, brand: 'Volvo' },
  { id: 18, brand: 'Mitsubishi' },
  { id: 19, brand: 'RAM' },
  { id: 20, brand: 'GWM' },
  { id: 21, brand: 'Kia' },
  { id: 22, brand: 'Audi' },
  { id: 23, brand: 'Chery' },
  { id: 24, brand: 'Land Rover' },
  { id: 25, brand: 'Mazda' },
  { id: 26, brand: 'Jaguar' },
  { id: 27, brand: 'Subaru' },
  { id: 28, brand: 'Mini' },
  { id: 29, brand: 'Porsche' },
  { id: 30, brand: 'Ferrari' },
  { id: 31, brand: 'Lamborghini' },
  { id: 32, brand: 'Tesla' },
  { id: 33, brand: 'Polestar' },
  { id: 34, brand: 'Honda' },
  { id: 35, brand: 'Toyota' },
  { id: 36, brand: 'BMW' },
  { id: 37, brand: 'Mercedes-Benz' },
  { id: 38, brand: 'Audi' },
  { id: 39, brand: 'Volkswagen' },
  { id: 40, brand: 'Chevrolet' },
  { id: 41, brand: 'Hyundai' },
  { id: 42, brand: 'Renault' },
  { id: 43, brand: 'Jeep' },
  { id: 44, brand: 'Nissan' },
  { id: 45, brand: 'BYD' },
  { id: 46, brand: 'Caoa Chery' },
  { id: 47, brand: 'Fiat' },
  { id: 48, brand: 'Ford' },
  { id: 49, brand: 'Mitsubishi' },
  { id: 50, brand: 'Peugeot' }
];


// Top 20 best-selling car models in Brazil
export const popularCars = [
  { id: 1, model: "Strada", brand: "Fiat" },
  { id: 2, model: "Polo", brand: "Volkswagen" },
  { id: 3, model: "Argo", brand: "Fiat" },
  { id: 4, model: "T-Cross", brand: "Volkswagen" },
  { id: 5, model: "HB20", brand: "Hyundai" },
  { id: 6, model: "Onix", brand: "Chevrolet" },
  { id: 7, model: "Mobi", brand: "Fiat" },
  { id: 8, model: "Creta", brand: "Hyundai" },
  { id: 9, model: "Corolla Cross", brand: "Toyota" },
  { id: 10, model: "Saveiro", brand: "Volkswagen" },
  { id: 11, model: "Compass", brand: "Jeep" },
  { id: 12, model: "Tracker", brand: "Chevrolet" },
  { id: 13, model: "Kwid", brand: "Renault" },
  { id: 14, model: "Fastback", brand: "Fiat" },
  { id: 15, model: "Toro", brand: "Fiat" },
  { id: 16, model: "Nivus", brand: "Volkswagen" },
  { id: 17, model: "Hilux", brand: "Toyota" },
  { id: 18, model: "HR-V", brand: "Honda" },
  { id: 19, model: "Kicks", brand: "Nissan" },
  { id: 20, model: "Onix Plus", brand: "Chevrolet" },
  { id: 21, model: "Creta", brand: "Hyundai" },  
  { id: 22, model: "Renegade", brand: "Jeep" },
  { id: 23, model: "Pulse", brand: "Fiat" },
  { id: 24, model: "Cronos", brand: "Fiat" },
  { id: 25, model: "Duster", brand: "Renault" },
  { id: 26, model: "Corolla", brand: "Toyota" },
  { id: 27, model: "Virtus", brand: "Volkswagen" },
  { id: 28, model: "C3", brand: "Citroën" },
  { id: 29, model: "Captur", brand: "Renault" },
  { id: 30, model: "Yaris Cross", brand: "Toyota" },
  { id: 31, model: "Edge", brand: "Ford" },
  { id: 32, model: "Argo Cross", brand: "Fiat" },
  { id: 33, model: "Creta Plus", brand: "Hyundai" },
  { id: 34, model: "Equinox", brand: "Chevrolet" },
  { id: 35, model: "Doblò", brand: "Fiat" },
  { id: 36, model: "Cobalt", brand: "Chevrolet" },
  { id: 37, model: "Lancer", brand: "Mitsubishi" },
  { id: 38, model: "Golf", brand: "Volkswagen" },
  { id: 39, model: "Sentra", brand: "Nissan" },
  { id: 40, model: "Soul", brand: "Kia" },
  { id: 41, model: "Jetta", brand: "Volkswagen" },
  { id: 42, model: "X1", brand: "BMW" },
  { id: 43, model: "Civic", brand: "Honda" },
  { id: 44, model: "City", brand: "Honda" },
  { id: 45, model: "Focus", brand: "Ford" },
  { id: 46, model: "Ranger", brand: "Ford" },
  { id: 47, model: "Toro (versão nova)", brand: "Fiat" },
  { id: 48, model: "Creta Sport", brand: "Hyundai" },
  { id: 49, model: "Renegade (versão top)", brand: "Jeep" },
  { id: 50, model: "Compass (versão premium)", brand: "Jeep" },
];

// Top 10 Motorcycle Brands in Brazil (2025)
export const popularMotorcycles = [
  { id: 1, model: "CG 160", brand: "Honda" },
  { id: 2, model: "Biz", brand: "Honda" },
  { id: 3, model: "Pop 110i", brand: "Honda" },
  { id: 4, model: "NXR 160 / Bros 160", brand: "Honda" },
  { id: 5, model: "Sport 110i", brand: "Mottu" },
  { id: 6, model: "CB 300F Twister", brand: "Honda" },
  { id: 7, model: "YBR 150 Factor", brand: "Yamaha" },
  { id: 8, model: "PCX 160", brand: "Honda" },
  { id: 9, model: "XRE 300 Sahara", brand: "Honda" },
  { id: 10, model: "Fazer 250", brand: "Yamaha" },
  { id: 11, model: "XTZ 250 Lander", brand: "Yamaha" },
  { id: 12, model: "Fazer 150", brand: "Yamaha" },
  { id: 13, model: "XRE 190", brand: "Honda" },
  { id: 14, model: "Elite 125", brand: "Honda" },
  { id: 15, model: "Crosser 150", brand: "Yamaha" },
  { id: 16, model: "SHI 175", brand: "Shineray" },
  { id: 17, model: "NMax 160", brand: "Yamaha" },
  { id: 18, model: "XY50", brand: "Shineray" },
  { id: 19, model: "XY150", brand: "Shineray" },
  { id: 20, model: "AZ1", brand: "Avelloz" },
  { id: 21, model: "YBR 125", brand: "Yamaha" },
  { id: 22, model: "XRE 300", brand: "Honda" },
  { id: 23, model: "CG 150", brand: "Honda" },
  { id: 24, model: "CG 125", brand: "Honda" },
  { id: 25, model: "Pop 100", brand: "Honda" }
];

export const motorcycleBrands = [
  { id: 1, brand: 'Honda' },
  { id: 2, brand: 'Yamaha' },
  { id: 3, brand: 'Shineray' },
  { id: 4, brand: 'Mottu' },
  { id: 5, brand: 'Royal Enfield' },
  { id: 6, brand: 'Bajaj' },
  { id: 7, brand: 'Haojue' },
  { id: 8, brand: 'BMW' },
  { id: 9, brand: 'Triumph' },
  { id: 10, brand: 'Avelloz' }
];

export const truckBrands = [
  { id: 1, brand: 'Volkswagen Caminhões e Ônibus' },
  { id: 2, brand: 'Mercedes-Benz' },
  { id: 3, brand: 'Volvo' },
  { id: 4, brand: 'Scania' },
  { id: 5, brand: 'DAF' },
  { id: 6, brand: 'Iveco' },
  { id: 7, brand: 'Ford' },
  { id: 8, brand: 'MAN' },
  { id: 9, brand: 'Agrale' },
  { id: 10, brand: 'Hino' },
  { id: 11, brand: 'Foton' },
  { id: 12, brand: 'Hyundai' },
  { id: 13, brand: 'Isuzu' },
  { id: 14, brand: 'Kia' },
  { id: 15, brand: 'Mitsubishi' },
  { id: 16, brand: 'Peugeot' },
  { id: 17, brand: 'Renault' },
  { id: 18, brand: 'Toyota' },
  { id: 19, brand: 'Chery' },
  { id: 20, brand: 'JAC Motors' },
];
export const truckModels = [
  { id: 1, model: 'Volvo FH 540', brand: 'Volvo' },
  { id: 2, model: 'DAF XF 530', brand: 'DAF' },
  { id: 3, model: 'Volvo FH 460', brand: 'Volvo' },
  { id: 4, model: 'Volvo VM 360', brand: 'Volvo' },
  { id: 5, model: 'Scania Super 460R', brand: 'Scania' },
  { id: 6, model: 'DAF XF 480', brand: 'DAF' },
  { id: 7, model: 'Volvo FH 500', brand: 'Volvo' },
  { id: 8, model: 'Mercedes-Benz Actros 2651', brand: 'Mercedes-Benz' },
  { id: 9, model: 'Scania R 450', brand: 'Scania' },
  { id: 10, model: 'Mercedes-Benz Atego 2730', brand: 'Mercedes-Benz' },
  { id: 11, model: 'DAF XF 105', brand: 'DAF' },
  { id: 12, model: 'Mercedes-Benz Accelo 1017', brand: 'Mercedes-Benz' },
  { id: 13, model: 'Volkswagen Delivery 11.180', brand: 'Volkswagen' },
  { id: 14, model: 'Volkswagen Constellation 26.260', brand: 'Volkswagen' },
  { id: 15, model: 'Scania R 500', brand: 'Scania' },
  { id: 16, model: 'Iveco S-Way 480', brand: 'Iveco' },
  { id: 17, model: 'Mercedes-Benz Atego 2429', brand: 'Mercedes-Benz' },
  { id: 18, model: 'Volkswagen Constellation 17.210', brand: 'Volkswagen' },
  { id: 19, model: 'Scania R 410', brand: 'Scania' },
  { id: 20, model: 'Iveco Stralis 460', brand: 'Iveco' },
];



export const vehicleColors = [
  { id: 1, color: "Branco" },
  { id: 2, color: "Preto" },
  { id: 3, color: "Prata" },
  { id: 4, color: "Cinza" },
  { id: 5, color: "Vermelho" },
  { id: 6, color: "Azul" },
  { id: 7, color: "Verde" },
  { id: 8, color: "Amarelo" },
  { id: 9, color: "Laranja" },
  { id: 10, color: "Marrom" },
  { id: 11, color: "Bege" },
  { id: 12, color: "Dourado" },
  { id: 13, color: "Roxo" },
  { id: 14, color: "Vinho" },
  { id: 15, color: "Rosa" },
  { id: 16, color: "Bronze" },
  { id: 17, color: "Azul-marinho" },
  { id: 18, color: "Azul claro" },
  { id: 19, color: "Cinza escuro" },
  { id: 20, color: "Champanhe" },
  { id: 21, color: "Grafite" },
  { id: 22, color: "Caramelo" },
  { id: 23, color: "Off-white" },
  { id: 24, color: "Turquesa" },
  { id: 25, color: "Verde-oliva" }
];


export const vehicleTypes = [
  { id: 1, type: "Carro" },
  { id: 2, type: "Moto" },
  { id: 3, type: "Caminhão" },
  { id: 4, type: "Ônibus" },
  { id: 5, type: "Van" },
  { id: 6, type: "Micro-ônibus" },
  { id: 7, type: "Pickup" },
  { id: 8, type: "SUV" },
  { id: 9, type: "Crossover" },
  { id: 10, type: "Furgão" },
  { id: 11, type: "Reboque" },
  { id: 12, type: "Trator" },
  { id: 13, type: "Bicicleta" },
  { id: 14, type: "Triciclo" },
  { id: 15, type: "Quadriciclo" },
  { id: 16, type: "Motoneta" },
  { id: 17, type: "Patinete elétrico" },
  { id: 18, type: "Carro elétrico" },
  { id: 19, type: "Caminhonete" }, // usado no Brasil como termo rural/pesado
  { id: 20, type: "Utilitário leve" }
];
 



export const initRegisterVehicle:Vehicle ={
  idVehicle:'',
  plate:'',
  color:'',
  vehicleType:'',
  model:'',
  brands:'',
  }
